#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/veux

PRODUCT_COPY_FILES += \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88006AA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88006AA1.prop \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88007AA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88007AA1.prop \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88007EA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88007EA1.prop \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88008BA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88008BA1.prop \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88106BA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88106BA1.prop \
    vendor/xiaomi/veux/proprietary/odm/etc/build_S88107BA1.prop:$(TARGET_COPY_OUT_ODM)/etc/build_S88107BA1.prop \
    vendor/xiaomi/veux/proprietary/recovery/root/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/goodix_cfg_group.bin \
    vendor/xiaomi/veux/proprietary/recovery/root/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/goodix_firmware.bin \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Bluetooth_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_General_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Global_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Handset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Hdmi_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Headset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_Speaker_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/aw882xx/QRD_global_aw882xx_workspaceFile.qwsp \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Bluetooth_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_General_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Global_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Handset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Hdmi_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Headset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_Speaker_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/global/fs19xx/QRD_global_fs19xx_workspaceFile.qwsp \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Bluetooth_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_General_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Global_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Handset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Hdmi_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Headset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_Speaker_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/holi-qrdsku1-snd-card/QRD_SKU1_workspaceFile.qwsp \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Bluetooth_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_General_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Global_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Handset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Hdmi_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Headset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_Speaker_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/aw882xx/QRD_india_aw882xx_workspaceFile.qwsp \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Bluetooth_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_General_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Global_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Handset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Hdmi_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Headset_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_Speaker_cal.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/india/fs19xx/QRD_india_fs19xx_workspaceFile.qwsp \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/veux/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/104_Meet.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/104_Meet.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/108_NorthernEurope.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/108_NorthernEurope.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/109_Rome.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/109_Rome.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/110_BlackGold.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/110_BlackGold.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/121_BBP.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/121_BBP.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/122_Mysterious.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/122_Mysterious.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/123_GreenOrange.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/123_GreenOrange.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/124_SummerDay.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/124_SummerDay.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/125_Latin.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/125_Latin.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/126_Fantasy.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/126_Fantasy.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/127_DustDream.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/127_DustDream.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/128_MongKok.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/128_MongKok.png \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden_i:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden_i \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden_ii:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden_ii \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden_in_i:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden_in_i \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/dof_mecp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dof_mecp.bin \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/intsense_config_undistort.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/intsense_config_undistort.bin \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/cap_model/ldc_cap_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_model/ldc_cap_cache \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/cap_model/ldc_cap_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_model/ldc_cap_model \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/cap_model/ldc_cap_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/cap_model/ldc_cap_policy \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/depth_model/capture_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/depth_model/capture_cache \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/depth_model/capture_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/depth_model/capture_model \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/depth_model/capture_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/depth_model/capture_policy \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/pre_model/ldc_pre_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/pre_model/ldc_pre_cache \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/pre_model/ldc_pre_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/pre_model/ldc_pre_model \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/pre_model/ldc_pre_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/pre_model/ldc_pre_policy \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/rt_model/preview_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_cache \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/rt_model/preview_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_model \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/model/rt_model/preview_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model/rt_model/preview_policy \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_gc02m1_macro_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_gc02m1_macro_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_imx355_ultra_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_imx355_ultra_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_ov16a1q_front_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_ov16a1q_front_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_10x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_2x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_4x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_6x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_aac_s5khm2_main_ii_8x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_ofilm_gc02m1_macro_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_ofilm_gc02m1_macro_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_qtech_imx355_ultra_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_qtech_imx355_ultra_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_ov16a1q_front_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_ov16a1q_front_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_10x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_2x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_4x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_6x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_India_sunny_s5khm2_main_i_8x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_gc02m1_macro_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_gc02m1_macro_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_imx355_ultra_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_imx355_ultra_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_ov16a1q_front_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_ov16a1q_front_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_10x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_2x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_4x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_6x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_aac_s5khm2_main_ii_8x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_gc02m1_macro_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_gc02m1_macro_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_10x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_2x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_4x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_6x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_ofilm_s5kgw3_main_i_8x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_qtech_imx355_ultra_ii.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_qtech_imx355_ultra_ii.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_ov16a1q_front_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_ov16a1q_front_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_10x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_10x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_2x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_2x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_4x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_4x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_6x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_6x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_8x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/morpho_lowlight_2.0_sunny_s5khm2_main_i_8x.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/vidhance_kernel1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_kernel1.bin \
    vendor/xiaomi/veux/proprietary/vendor/etc/camera/vidhance_kernel2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_kernel2.bin \
    vendor/xiaomi/veux/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/init/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.batterysecret.rc \
    vendor/xiaomi/veux/proprietary/vendor/etc/init/init.veux.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.veux.nfc.rc \
    vendor/xiaomi/veux/proprietary/vendor/etc/init/vendor.silead.hardware.fingerprintext@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.silead.hardware.fingerprintext@1.0-service.rc \
    vendor/xiaomi/veux/proprietary/vendor/etc/libnfc-nci-pn557.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci-pn557.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/libnfc-nci-sn100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci-sn100.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/libnfc-pn557.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-pn557.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/libnfc-sn100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-sn100.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/qdcm_calib_data_xiaomi_k6s_38_0c_0a_fhd_dsc_video_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_xiaomi_k6s_38_0c_0a_fhd_dsc_video_dsi_panel.xml \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/holi_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/holi_default_sensors.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/holi_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/holi_dynamic_sensors.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/holi_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/holi_power_0.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sensor_devinfo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sensor_devinfo.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/strait_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_default_sensors.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/strait_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_dynamic_sensors.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/strait_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_power_0.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_ak991x.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_ak991x.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_bu27030.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_bu27030.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_icm4x6xx.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_icm4x6xx.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_lsm6dso_0.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_qmc6308.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_qmc6308.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/config/veux_qrd_sx933x.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veux_qrd_sx933x.json \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-extreme.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-extreme.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-high.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-nevigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nevigation.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermal-youtube.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-youtube.conf \
    vendor/xiaomi/veux/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw8624_osc_rtp_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_osc_rtp_24K_5s.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw8624_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/aw882xx_pid_2113_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_pid_2113_acf.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/fs1958.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1958.fsm \
    vendor/xiaomi/veux/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/xiaomi/veux/proprietary/vendor/firmware/osc_rtp_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/osc_rtp_24K_5s.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_aac_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_aac_gc02m1.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_aac_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_aac_imx355.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_aac_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_aac_ov16a1q.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_aac_s5khm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_aac_s5khm2.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_ofilm_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_ofilm_gc02m1.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_ofilm_s5kgw3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_ofilm_s5kgw3.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_qtech_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_qtech_imx355.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_sunny_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_sunny_ov16a1q.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.sensormodule.veux_sunny_s5khm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.veux_sunny_s5khm2.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_aac_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_aac_gc02m1.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_aac_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_aac_imx355.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_aac_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_aac_ov16a1q.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_aac_s5khm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_aac_s5khm2.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_ofilm_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_ofilm_gc02m1.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_ofilm_s5kgw3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_ofilm_s5kgw3.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_qtech_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_qtech_imx355.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_sunny_ov16a1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_sunny_ov16a1q.bin \
    vendor/xiaomi/veux/proprietary/vendor/lib64/camera/com.qti.tuned.veux_sunny_s5khm2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.veux_sunny_s5khm2.bin

PRODUCT_PACKAGES += \
    libcamxexternalformatutils \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libaudcal \
    android.hardware.secure_element@1.0-impl \
    com.qti.eeprom.gt24p128c2csli_imx766 \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.truly_cmb433 \
    com.qti.flash.ktd2691 \
    com.qti.flash.lm36011 \
    com.qti.flash.lm3644 \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx376 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx476 \
    com.qti.sensor.imx481 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx576 \
    com.qti.sensor.imx577 \
    com.qti.sensor.imx586 \
    com.qti.sensor.imx766 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov12a10_front \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov6211_master \
    com.qti.sensor.ov6211_slave \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.ov8856_master \
    com.qti.sensor.ov8856_slave \
    com.qti.sensor.ov9282_master \
    com.qti.sensor.ov9282_slave \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k2x5sp \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5k3p9 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.s5k5e9yu05 \
    com.qti.sensor.s5k5e9yx04 \
    com.qti.sensor.s5kjd1sp \
    com.qti.sensor.veux_aac_gc02m1_macro \
    com.qti.sensor.veux_aac_imx355_ultra \
    com.qti.sensor.veux_aac_ov16a1q_front \
    com.qti.sensor.veux_aac_s5khm2_main \
    com.qti.sensor.veux_ofilm_gc02m1_macro \
    com.qti.sensor.veux_ofilm_s5kgw3_main \
    com.qti.sensor.veux_qtech_imx355_ultra \
    com.qti.sensor.veux_sunny_ov16a1q_front \
    com.qti.sensor.veux_sunny_s5khm2_main \
    com.jiigan.node.realtimebokeh \
    com.mi.node.mipitounpacketraw \
    com.mi.node.superlowlightraw \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.mialgocontrol \
    com.qti.node.mimovie \
    com.qti.node.ml \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.processing \
    libdepthmapwrapper \
    libdepthmapwrapper_secure \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.kamorta \
    com.qti.feature2.gs.kodiak \
    com.qti.feature2.gs.mannar \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rawsupernight \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.kamorta \
    com.qti.settings.kodiak \
    com.qti.settings.mannar \
    com.qti.settings.sdm865 \
    com.qti.settings.sm8350 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.override \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    fingerprint.silead.default \
    libgf_hal \
    vendor.qti.esepowermanager@1.1-impl \
    jcos_nq_client \
    libHalSuperSensorServer \
    libSuperSensor \
    libSuperSensorCPU \
    libaidenoiser \
    libaidenoiserv2 \
    libalCFR \
    libalLDC \
    libalhLDC \
    libanc_dc_base \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_super_night_raw \
    libbitmlengine \
    libbitmlenginev2 \
    libc++_shared \
    libcamera_nn_stub \
    libcamera_scene \
    libcamerapostproc \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libdepthcomputation \
    libdng_sdk2vendor \
    libft2vendor \
    libgf_ca \
    libgoodixhwfingerprint \
    libipebpsstriping \
    libipebpsstriping170 \
    libjpege \
    libmctfengine_stub \
    libmfec \
    libmialgoengine \
    libmibokeh_712 \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_Lowlight \
    libmpbase \
    libofflinedump \
    libofflinelog \
    libopencv \
    libopestriping \
    libos \
    libpn557_fw \
    libqll10 \
    libqllengine \
    libremosaic_wrapper \
    libremosaiclib \
    libsl_fp_impl \
    libsn100u_fw \
    libspectre \
    libswregistrationalgo \
    libtfestriping \
    libthreadutils \
    libvideofilter_only \
    libvidhance \
    libwa_depth \
    libwa_dof \
    libwa_refocus \
    libwa_rtdof \
    libwa_widelens_undistort \
    libxml2_vendor \
    ls_nq_client \
    se_nq_extn_client \
    sensors.elliptic \
    sensors.ssc \
    sensors.touch.detect \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.silead.hardware.fingerprintext@1.0 \
    vendor_lib_rfsa_adsp_bm2n06_bin \
    vendor_lib_rfsa_adsp_bm2n08_bin \
    vendor_lib_rfsa_adsp_bm2n12_bin \
    vendor_lib_rfsa_adsp_bm2n13_bin \
    vendor_lib_rfsa_adsp_bm2n14_bin \
    vendor_lib_rfsa_adsp_bm2n15_bin \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDADV_Encoder_so \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDAD_Speech_Decoder_so \
    vendor_lib_rfsa_adsp_capi_v2_dap_cpdp_so \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libhexagon_nn_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    vendor_lib_rfsa_adsp_misound_karaoke_res_bin \
    vendor_lib_rfsa_adsp_misound_karaokemix_res_bin \
    vendor_lib_rfsa_adsp_misound_res_bin \
    vendor_lib_rfsa_adsp_misound_res_headphone_bin \
    vendor_lib_rfsa_adsp_misound_res_spk_bin \
    batterysecret \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.secure_element@1.2-service \
    vendor.silead.hardware.fingerprintext@1.0-service
